// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace OctobridgeEF.Models;

public partial class CodedValue
{
    public string GroupName { get; set; }

    public string Value { get; set; }

    public string Description { get; set; }
}
