// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace OctobridgeEF.Models;

public partial class GetAttachmentsByNameResult
{
    public int Id { get; set; }
    [StringLength(255)]
    public string Filename { get; set; }
    [StringLength(100)]
    public string Filetype { get; set; }
    public long Length { get; set; }
    public DateTime RecordCreated { get; set; }
}
