// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace OctobridgeEF.Models;

public partial class GetCustomersByNameResult
{
    public int Id { get; set; }
    [StringLength(100)]
    public string FirstName { get; set; }
    [StringLength(100)]
    public string LastName { get; set; }
    [StringLength(50)]
    public string MiddleName { get; set; }
    [StringLength(60)]
    public string AddressLine1 { get; set; }
    [StringLength(60)]
    public string AddressLine2 { get; set; }
    [StringLength(30)]
    public string City { get; set; }
    [StringLength(15)]
    public string PostalCode { get; set; }
    [StringLength(25)]
    public string Telephone { get; set; }
    [StringLength(25)]
    public string Email { get; set; }
    public DateTime RecordCreated { get; set; }
    public DateTime RecordModified { get; set; }
}
