// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace OctobridgeEF.Models;

public partial class Payment
{
    public int Id { get; set; }

    public int OrderId { get; set; }

    public string TransactionId { get; set; }

    public string Gateway { get; set; }

    public string CardType { get; set; }

    public string CardNumber { get; set; }

    public string ExpiryDate { get; set; }

    public decimal Amount { get; set; }

    public DateTime RecordCreated { get; set; }

    public DateTime RecordModified { get; set; }

    public virtual Order Order { get; set; }
}
