// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace OctobridgeEF.Models;

public partial class ProductCategory
{
    public int ProductCategoryId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public DateTime RecordCreated { get; set; }

    public DateTime RecordModified { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}
