// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace OctobridgeEF.Models;

public partial class UpdateOrderByIDResult
{
    public int Id { get; set; }
    [StringLength(50)]
    public string OrderStatus { get; set; }
    public int CustomerId { get; set; }
    [Column("FreightAmount", TypeName = "money")]
    public decimal FreightAmount { get; set; }
    [Column("SubTotal", TypeName = "money")]
    public decimal SubTotal { get; set; }
    [Column("TotalDue", TypeName = "money")]
    public decimal TotalDue { get; set; }
    public DateTime? PaymentDate { get; set; }
    public DateTime? ShippedDate { get; set; }
    public DateTime? CancelDate { get; set; }
    public DateTime RecordCreated { get; set; }
    public DateTime RecordModified { get; set; }
}
