// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace OctobridgeEF.Models;

public partial class GetOrderDetailsByOrderIdResult
{
    public int LineId { get; set; }
    public int OrderId { get; set; }
    public int ProductId { get; set; }
    [Column("UnitPrice", TypeName = "money")]
    public decimal UnitPrice { get; set; }
    public int Quantity { get; set; }
    public DateTime RecordCreated { get; set; }
    public DateTime RecordModified { get; set; }
}
