// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace OctobridgeEF.Models;

public partial class GetProductByIdResult
{
    public int ProductId { get; set; }
    [StringLength(100)]
    public string Name { get; set; }
    [StringLength(50)]
    public string ProductNumber { get; set; }
    public int ProductCategoryId { get; set; }
    [Column("Cost", TypeName = "money")]
    public decimal Cost { get; set; }
    public DateTime RecordCreated { get; set; }
    public DateTime RecordModified { get; set; }
}
