// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace OctobridgeEF.Models;

public partial interface IOctobridgeContextProcedures
{
    Task<int> AddAttachmentAsync(string filename, string filetype, long? filelength, byte[] filedata, OutputParameter<int?> id, OutputParameter<DateTime?> dt, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    Task<int> AddCustomerAsync(string firstName, string lastName, string middleName, string addressLine1, string addressLine2, string city, string postalCode, string telephone, string email, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    Task<int> AddOrderAsync(string orderStatus, int? customerId, decimal? freightAmount, decimal? subTotal, decimal? totalDue, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    Task<int> AddProductAsync(string name, string productNumber, int? productCategoryId, decimal? cost, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    Task<int> DeleteAttachmentByIdAsync(int? id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    Task<int> DeleteCustomerByIdAsync(int? id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    Task<int> DeleteOrderByIdAsync(int? id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    Task<int> DeleteProductByIdAsync(int? id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    Task<List<GetAttachmentDataResult>> GetAttachmentDataAsync(int? id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    Task<List<GetAttachmentsByNameResult>> GetAttachmentsByNameAsync(string filename, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    Task<List<GetCustomersByNameResult>> GetCustomersByNameAsync(string lastName, string firstName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    Task<List<GetOrderDetailsByOrderIdResult>> GetOrderDetailsByOrderIdAsync(int? orderId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    Task<List<GetProductByIdResult>> GetProductByIdAsync(int? id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    Task<List<GetProductsByNameNumberResult>> GetProductsByNameNumberAsync(string name, string productNumber, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    Task<List<UpdateCustomerByIDResult>> UpdateCustomerByIDAsync(int? id, string firstName, string lastName, string middleName, string addressLine1, string addressLine2, string city, string postalCode, string telephone, string email, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    Task<List<UpdateOrderByIDResult>> UpdateOrderByIDAsync(int? id, string orderStatus, DateTime? orderDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    Task<List<UpdateProductByIdResult>> UpdateProductByIdAsync(int? productId, string name, string productNumber, int? productCategoryId, decimal? cost, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
}
